name: Deploy to S3 or ECS

on:
  push:
    paths:
      - "dist/**"
      - "Dockerfile"

jobs:
  # S3 배포 작업
  deploy-s3:
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.modified, 'dist/') # dist 폴더 변경 시에만 실행
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Upload files to S3
      - name: Upload files to S3
        run: |
          aws s3 sync dist s3://testpractice1020/ --delete

      # 4. List uploaded files (optional)
      - name: List uploaded files
        run: aws s3 ls s3://testpractice1020/ --recursive

  # Docker + ECS 배포 작업
  deploy-ecs:
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.modified, 'Dockerfile') # Dockerfile 변경 시에만 실행
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t practice-express-docker .

      # 4. Tag Docker image for ECR
      - name: Tag Docker image
        run: |
          docker tag practice-express-docker:latest${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/practice-express-docker:latest

      # 5. Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/practice-express-docker:latest

      # 6. Update ECS Service
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster practice-express-docker \
            --service practice-express-service \
            --force-new-deployment
